name: Add needs-triage label

on:
  issues:
    types:
      - opened

jobs:
  needs-triage:
    runs-on: ubuntu-latest
    steps:
      - name: Add needs-triage label
        if: join(github.event.issue.labels) == ''
        run: |
          curl --request POST \
          --url 'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels' \
          --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --header 'Accept: application/vnd.github.v3+json' \
          --data-raw '{ "labels": ["needs: triage"] }'
